alias vi="nvim"
alias ls="eza --group-directories-first --icons"
alias ll="eza --group-directories-first --icons -l -a"
alias lt="eza --group-directories-first --icons --tree"
alias ze="zellij --layout compact"
alias canvas="python3 ~/.canvaspy/canvas.py"

PROMPT='%F{green}%n %F{magenta}%~%f%F{green}$%f '


# Conditionally enable conda/mamba only if available
if command -v conda >/dev/null 2>&1 \
   || [ -x "/opt/homebrew/Caskroom/mambaforge/base/bin/conda" ] \
   || [ -f "/opt/homebrew/Caskroom/mambaforge/base/etc/profile.d/conda.sh" ]; then

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/Caskroom/mambaforge/base/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/Caskroom/mambaforge/base/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/Caskroom/mambaforge/base/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/Caskroom/mambaforge/base/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/opt/homebrew/Caskroom/mambaforge/base/etc/profile.d/mamba.sh" ]; then
    . "/opt/homebrew/Caskroom/mambaforge/base/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

fi
