
alias vi="nvim"
alias ls="eza --group-directories-first --icons"
alias ll="eza --group-directories-first --icons -l -a"
alias lt="eza --group-directories-first --icons --tree"
alias ze="zellij"

PROMPT='%F{green}%n %F{magenta}%~%f%F{green}$%f '
