
alias vi="nvim"
alias ls="eza --group-directories-first --icons"
alias ll="eza --group-directories-first --icons -l -a"
alias lt="eza --group-directories-first --icons --tree"

PROMPT='%F{cyan}%n%F{magenta}@%F{cyan}%m%f%F{magenta}$%f '
